# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170326_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
