# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-26 14:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0004_auto_20170326_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('xingming', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
            ],
            options={
                'db_table': 'user_profile',
                'default_related_name': 'profile',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
