# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
